name: flint
description: Opinionated Flutter lint rules that catch common anti-patterns. Zero config, just add and go.
version: 0.1.0
homepage: https://github.com/suojae/flint
repository: https://github.com/suojae/flint
issue_tracker: https://github.com/suojae/flint/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer:
  custom_lint_builder: ^0.8.1
dev_dependencies:
  lints: ^6.1.0
